name: Update Docker Image

env:
  DH_USER: bestian
  DH_REPO: prometheus.folder.list.exporter
  DH_TOKEN: ${{ secrets.DH_TOKEN }}
  DH_PLATFORMS: "linux/amd64,linux/arm64"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - master

jobs:
  push:
    name: 'Build and Push Image'

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - run: echo "XTIME_NOW=$(date +'%Y.%m.%d-%H.%M.%S')" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ env.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DH_USER }}/${{ env.DH_REPO }}:${{ env.XTIME_NOW }}
            ${{ env.DH_USER }}/${{ env.DH_REPO }}:latest
          platforms: ${{ env.DH_PLATFORMS }}
